//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorresApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangaugeResource_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangaugeResource_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CorresApp.Resources.LangaugeResource.ar", typeof(LangaugeResource_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العمليه بنجاح.
        /// </summary>
        internal static string ActionCompledMsg {
            get {
                return ResourceManager.GetString("ActionCompledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطبيق البحث.
        /// </summary>
        internal static string ApplySearch {
            get {
                return ResourceManager.GetString("ApplySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعتماد.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحضور.
        /// </summary>
        internal static string Attandees {
            get {
                return ResourceManager.GetString("Attandees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        internal static string Attatchements {
            get {
                return ResourceManager.GetString("Attatchements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقويم.
        /// </summary>
        internal static string Calender {
            get {
                return ResourceManager.GetString("Calender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللجنة.
        /// </summary>
        internal static string Comitee {
            get {
                return ResourceManager.GetString("Comitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتمله.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المراسلة.
        /// </summary>
        internal static string CorrespondenceDetails {
            get {
                return ResourceManager.GetString("CorrespondenceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        internal static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراسلات مطلوب الرد عليها.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التأخير.
        /// </summary>
        internal static string Delayed {
            get {
                return ResourceManager.GetString("Delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهه.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهات المرسل إليها.
        /// </summary>
        internal static string DestinationEntities {
            get {
                return ResourceManager.GetString("DestinationEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإنتهاء.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد لديك صلاحيات على نظام المراسلات، الرجاء مراجعة مسؤول النظام..
        /// </summary>
        internal static string DontHaveSitesMsg {
            get {
                return ResourceManager.GetString("DontHaveSitesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موظفين في ال cc.
        /// </summary>
        internal static string EmployeeInCC {
            get {
                return ResourceManager.GetString("EmployeeInCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى الساعة.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متابعة رسائل المراجعة.
        /// </summary>
        internal static string FollowingMOMReview {
            get {
                return ResourceManager.GetString("FollowingMOMReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسة.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق الوارد.
        /// </summary>
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوارد الخارجي.
        /// </summary>
        internal static string IncomingExternal {
            get {
                return ResourceManager.GetString("IncomingExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوارد الداخلي.
        /// </summary>
        internal static string IncomingInternal {
            get {
                return ResourceManager.GetString("IncomingInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري العمل.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليمات.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاجتماع.
        /// </summary>
        internal static string MeetingDate {
            get {
                return ResourceManager.GetString("MeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الاجتماع.
        /// </summary>
        internal static string MeetingDetails {
            get {
                return ResourceManager.GetString("MeetingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الاجتماع.
        /// </summary>
        internal static string MeetingPlace {
            get {
                return ResourceManager.GetString("MeetingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد مراسلات وارده.
        /// </summary>
        internal static string NoInbox {
            get {
                return ResourceManager.GetString("NoInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد انترنت.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد عناصر.
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد لديك اشعارات.
        /// </summary>
        internal static string NoNotificationsFound {
            get {
                return ResourceManager.GetString("NoNotificationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  توجد مراسلات صادره.
        /// </summary>
        internal static string NoOutbox {
            get {
                return ResourceManager.GetString("NoOutbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإشعارات.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجتماع الكتروني.
        /// </summary>
        internal static string OnlineMeeting {
            get {
                return ResourceManager.GetString("OnlineMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق الصادر.
        /// </summary>
        internal static string Outbox {
            get {
                return ResourceManager.GetString("Outbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصادر الخارجي.
        /// </summary>
        internal static string OutgoingExternal {
            get {
                return ResourceManager.GetString("OutgoingExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الانتظار.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السبب.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفض.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراسلات ذات الصلة.
        /// </summary>
        internal static string RelatedCorrespondences {
            get {
                return ResourceManager.GetString("RelatedCorrespondences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرجاع.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الكلمه المفتاحيه.
        /// </summary>
        internal static string SearchValue {
            get {
                return ResourceManager.GetString("SearchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رأيك.
        /// </summary>
        internal static string SendFeedBack {
            get {
                return ResourceManager.GetString("SendFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال التوقيع.
        /// </summary>
        internal static string SendSignature {
            get {
                return ResourceManager.GetString("SendSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال الي الرئيس.
        /// </summary>
        internal static string SendToPresident {
            get {
                return ResourceManager.GetString("SendToPresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في السيرفر.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في السيرفر او  لا يوجد انترنت.
        /// </summary>
        internal static string ServerErrorOrNoInternetConnection {
            get {
                return ResourceManager.GetString("ServerErrorOrNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت .
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوقيع.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الساعة.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الي.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمه اليوم.
        /// </summary>
        internal static string TodaysList {
            get {
                return ResourceManager.GetString("TodaysList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحدة.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدم الاسم.
        /// </summary>
        internal static string UseMyName {
            get {
                return ResourceManager.GetString("UseMyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سير العمليات.
        /// </summary>
        internal static string WorkFlow {
            get {
                return ResourceManager.GetString("WorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك مهمات لهذا اليوم.
        /// </summary>
        internal static string YouHaveNOTasksForTheseDay {
            get {
                return ResourceManager.GetString("YouHaveNOTasksForTheseDay", resourceCulture);
            }
        }
    }
}
