//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorresApp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangaugeResource_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangaugeResource_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CorresApp.Resources.LangaugeResource.ar", typeof(LangaugeResource_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IncomingExternal {
            get {
                return ResourceManager.GetString("IncomingExternal", resourceCulture);
            }
        }
        
        internal static string OutgoingExternal {
            get {
                return ResourceManager.GetString("OutgoingExternal", resourceCulture);
            }
        }
        
        internal static string Delayed {
            get {
                return ResourceManager.GetString("Delayed", resourceCulture);
            }
        }
        
        internal static string IncomingInternal {
            get {
                return ResourceManager.GetString("IncomingInternal", resourceCulture);
            }
        }
        
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        internal static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        internal static string Outbox {
            get {
                return ResourceManager.GetString("Outbox", resourceCulture);
            }
        }
        
        internal static string Calender {
            get {
                return ResourceManager.GetString("Calender", resourceCulture);
            }
        }
        
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string CorrespondenceDetails {
            get {
                return ResourceManager.GetString("CorrespondenceDetails", resourceCulture);
            }
        }
        
        internal static string WorkFlow {
            get {
                return ResourceManager.GetString("WorkFlow", resourceCulture);
            }
        }
        
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        internal static string DestinationEntities {
            get {
                return ResourceManager.GetString("DestinationEntities", resourceCulture);
            }
        }
        
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        internal static string EmployeeInCC {
            get {
                return ResourceManager.GetString("EmployeeInCC", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        internal static string Attatchements {
            get {
                return ResourceManager.GetString("Attatchements", resourceCulture);
            }
        }
        
        internal static string RelatedCorrespondences {
            get {
                return ResourceManager.GetString("RelatedCorrespondences", resourceCulture);
            }
        }
        
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        internal static string TodaysList {
            get {
                return ResourceManager.GetString("TodaysList", resourceCulture);
            }
        }
        
        internal static string YouHaveNOTasksForTheseDay {
            get {
                return ResourceManager.GetString("YouHaveNOTasksForTheseDay", resourceCulture);
            }
        }
        
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        internal static string ServerErrorOrNoInternetConnection {
            get {
                return ResourceManager.GetString("ServerErrorOrNoInternetConnection", resourceCulture);
            }
        }
        
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string UseMyName {
            get {
                return ResourceManager.GetString("UseMyName", resourceCulture);
            }
        }
        
        internal static string MeetingDetails {
            get {
                return ResourceManager.GetString("MeetingDetails", resourceCulture);
            }
        }
        
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        internal static string Comitee {
            get {
                return ResourceManager.GetString("Comitee", resourceCulture);
            }
        }
        
        internal static string MeetingPlace {
            get {
                return ResourceManager.GetString("MeetingPlace", resourceCulture);
            }
        }
        
        internal static string MeetingDate {
            get {
                return ResourceManager.GetString("MeetingDate", resourceCulture);
            }
        }
        
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        internal static string OnlineMeeting {
            get {
                return ResourceManager.GetString("OnlineMeeting", resourceCulture);
            }
        }
        
        internal static string Attandees {
            get {
                return ResourceManager.GetString("Attandees", resourceCulture);
            }
        }
        
        internal static string FollowingMOMReview {
            get {
                return ResourceManager.GetString("FollowingMOMReview", resourceCulture);
            }
        }
        
        internal static string SendSignature {
            get {
                return ResourceManager.GetString("SendSignature", resourceCulture);
            }
        }
        
        internal static string SendToPresident {
            get {
                return ResourceManager.GetString("SendToPresident", resourceCulture);
            }
        }
        
        internal static string NoNotificationsFound {
            get {
                return ResourceManager.GetString("NoNotificationsFound", resourceCulture);
            }
        }
        
        internal static string NoInbox {
            get {
                return ResourceManager.GetString("NoInbox", resourceCulture);
            }
        }
        
        internal static string NoOutbox {
            get {
                return ResourceManager.GetString("NoOutbox", resourceCulture);
            }
        }
        
        internal static string SendFeedBack {
            get {
                return ResourceManager.GetString("SendFeedBack", resourceCulture);
            }
        }
        
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        internal static string ActionCompledMsg {
            get {
                return ResourceManager.GetString("ActionCompledMsg", resourceCulture);
            }
        }
        
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        internal static string ApplySearch {
            get {
                return ResourceManager.GetString("ApplySearch", resourceCulture);
            }
        }
        
        internal static string SearchValue {
            get {
                return ResourceManager.GetString("SearchValue", resourceCulture);
            }
        }
    }
}
